##########################################
# Dockerfile for AWS CLI container
# Based on insightdatascience/python2
###########################################
FROM insightdatascience/python2

MAINTAINER Austin Ouyang

RUN pip install awscli
RUN pip install --upgrade awscli
RUN apt-get install -y groff
